// This file is autogenerated. Do not edit it!

use Color;

static COLORS: Map<Color> = Map {
    key: 3213172566270843353,
    disps: &[
        (3, 123),
        (2, 11),
        (1, 0),
        (1, 21),
        (0, 49),
        (2, 57),
        (2, 85),
        (1, 0),
        (0, 36),
        (0, 11),
        (7, 112),
        (24, 52),
        (0, 0),
        (0, 6),
        (1, 69),
        (0, 88),
        (1, 70),
        (0, 42),
        (9, 94),
        (0, 42),
        (0, 88),
        (5, 96),
        (2, 144),
        (2, 7),
        (3, 103),
        (1, 68),
        (0, 2),
        (0, 69),
        (0, 111),
        (0, 0),
    ],
    entries: &[
        (
            "lawngreen",
            Color {
                red: 124,
                green: 252,
                blue: 0,
            },
        ),
        (
            "black",
            Color {
                red: 0,
                green: 0,
                blue: 0,
            },
        ),
        (
            "dimgray",
            Color {
                red: 105,
                green: 105,
                blue: 105,
            },
        ),
        (
            "darkkhaki",
            Color {
                red: 189,
                green: 183,
                blue: 107,
            },
        ),
        (
            "dodgerblue",
            Color {
                red: 30,
                green: 144,
                blue: 255,
            },
        ),
        (
            "darkolivegreen",
            Color {
                red: 85,
                green: 107,
                blue: 47,
            },
        ),
        (
            "coral",
            Color {
                red: 255,
                green: 127,
                blue: 80,
            },
        ),
        (
            "slateblue",
            Color {
                red: 106,
                green: 90,
                blue: 205,
            },
        ),
        (
            "powderblue",
            Color {
                red: 176,
                green: 224,
                blue: 230,
            },
        ),
        (
            "orange",
            Color {
                red: 255,
                green: 165,
                blue: 0,
            },
        ),
        (
            "red",
            Color {
                red: 255,
                green: 0,
                blue: 0,
            },
        ),
        (
            "palegreen",
            Color {
                red: 152,
                green: 251,
                blue: 152,
            },
        ),
        (
            "lightseagreen",
            Color {
                red: 32,
                green: 178,
                blue: 170,
            },
        ),
        (
            "lightgray",
            Color {
                red: 211,
                green: 211,
                blue: 211,
            },
        ),
        (
            "peru",
            Color {
                red: 205,
                green: 133,
                blue: 63,
            },
        ),
        (
            "lavender",
            Color {
                red: 230,
                green: 230,
                blue: 250,
            },
        ),
        (
            "indigo",
            Color {
                red: 75,
                green: 0,
                blue: 130,
            },
        ),
        (
            "darkmagenta",
            Color {
                red: 139,
                green: 0,
                blue: 139,
            },
        ),
        (
            "palegoldenrod",
            Color {
                red: 238,
                green: 232,
                blue: 170,
            },
        ),
        (
            "darkseagreen",
            Color {
                red: 143,
                green: 188,
                blue: 143,
            },
        ),
        (
            "mediumpurple",
            Color {
                red: 147,
                green: 112,
                blue: 219,
            },
        ),
        (
            "yellowgreen",
            Color {
                red: 154,
                green: 205,
                blue: 50,
            },
        ),
        (
            "orchid",
            Color {
                red: 218,
                green: 112,
                blue: 214,
            },
        ),
        (
            "paleturquoise",
            Color {
                red: 175,
                green: 238,
                blue: 238,
            },
        ),
        (
            "mediumblue",
            Color {
                red: 0,
                green: 0,
                blue: 205,
            },
        ),
        (
            "firebrick",
            Color {
                red: 178,
                green: 34,
                blue: 34,
            },
        ),
        (
            "bisque",
            Color {
                red: 255,
                green: 228,
                blue: 196,
            },
        ),
        (
            "plum",
            Color {
                red: 221,
                green: 160,
                blue: 221,
            },
        ),
        (
            "ivory",
            Color {
                red: 255,
                green: 255,
                blue: 240,
            },
        ),
        (
            "salmon",
            Color {
                red: 250,
                green: 128,
                blue: 114,
            },
        ),
        (
            "slategray",
            Color {
                red: 112,
                green: 128,
                blue: 144,
            },
        ),
        (
            "lightgreen",
            Color {
                red: 144,
                green: 238,
                blue: 144,
            },
        ),
        (
            "violet",
            Color {
                red: 238,
                green: 130,
                blue: 238,
            },
        ),
        (
            "darksalmon",
            Color {
                red: 233,
                green: 150,
                blue: 122,
            },
        ),
        (
            "aliceblue",
            Color {
                red: 240,
                green: 248,
                blue: 255,
            },
        ),
        (
            "oldlace",
            Color {
                red: 253,
                green: 245,
                blue: 230,
            },
        ),
        (
            "lightgoldenrodyellow",
            Color {
                red: 250,
                green: 250,
                blue: 210,
            },
        ),
        (
            "cadetblue",
            Color {
                red: 95,
                green: 158,
                blue: 160,
            },
        ),
        (
            "papayawhip",
            Color {
                red: 255,
                green: 239,
                blue: 213,
            },
        ),
        (
            "purple",
            Color {
                red: 128,
                green: 0,
                blue: 128,
            },
        ),
        (
            "lightskyblue",
            Color {
                red: 135,
                green: 206,
                blue: 250,
            },
        ),
        (
            "wheat",
            Color {
                red: 245,
                green: 222,
                blue: 179,
            },
        ),
        (
            "darkslategrey",
            Color {
                red: 47,
                green: 79,
                blue: 79,
            },
        ),
        (
            "teal",
            Color {
                red: 0,
                green: 128,
                blue: 128,
            },
        ),
        (
            "cornsilk",
            Color {
                red: 255,
                green: 248,
                blue: 220,
            },
        ),
        (
            "lightblue",
            Color {
                red: 173,
                green: 216,
                blue: 230,
            },
        ),
        (
            "lemonchiffon",
            Color {
                red: 255,
                green: 250,
                blue: 205,
            },
        ),
        (
            "darkred",
            Color {
                red: 139,
                green: 0,
                blue: 0,
            },
        ),
        (
            "royalblue",
            Color {
                red: 65,
                green: 105,
                blue: 225,
            },
        ),
        (
            "mediumseagreen",
            Color {
                red: 60,
                green: 179,
                blue: 113,
            },
        ),
        (
            "rosybrown",
            Color {
                red: 188,
                green: 143,
                blue: 143,
            },
        ),
        (
            "linen",
            Color {
                red: 250,
                green: 240,
                blue: 230,
            },
        ),
        (
            "cornflowerblue",
            Color {
                red: 100,
                green: 149,
                blue: 237,
            },
        ),
        (
            "indianred",
            Color {
                red: 205,
                green: 92,
                blue: 92,
            },
        ),
        (
            "palevioletred",
            Color {
                red: 219,
                green: 112,
                blue: 147,
            },
        ),
        (
            "turquoise",
            Color {
                red: 64,
                green: 224,
                blue: 208,
            },
        ),
        (
            "gold",
            Color {
                red: 255,
                green: 215,
                blue: 0,
            },
        ),
        (
            "aquamarine",
            Color {
                red: 127,
                green: 255,
                blue: 212,
            },
        ),
        (
            "seashell",
            Color {
                red: 255,
                green: 245,
                blue: 238,
            },
        ),
        (
            "darkturquoise",
            Color {
                red: 0,
                green: 206,
                blue: 209,
            },
        ),
        (
            "honeydew",
            Color {
                red: 240,
                green: 255,
                blue: 240,
            },
        ),
        (
            "tan",
            Color {
                red: 210,
                green: 180,
                blue: 140,
            },
        ),
        (
            "antiquewhite",
            Color {
                red: 250,
                green: 235,
                blue: 215,
            },
        ),
        (
            "aqua",
            Color {
                red: 0,
                green: 255,
                blue: 255,
            },
        ),
        (
            "tomato",
            Color {
                red: 255,
                green: 99,
                blue: 71,
            },
        ),
        (
            "lightslategray",
            Color {
                red: 119,
                green: 136,
                blue: 153,
            },
        ),
        (
            "green",
            Color {
                red: 0,
                green: 128,
                blue: 0,
            },
        ),
        (
            "darkblue",
            Color {
                red: 0,
                green: 0,
                blue: 139,
            },
        ),
        (
            "slategrey",
            Color {
                red: 112,
                green: 128,
                blue: 144,
            },
        ),
        (
            "peachpuff",
            Color {
                red: 255,
                green: 218,
                blue: 185,
            },
        ),
        (
            "darkslategray",
            Color {
                red: 47,
                green: 79,
                blue: 79,
            },
        ),
        (
            "darkgoldenrod",
            Color {
                red: 184,
                green: 134,
                blue: 11,
            },
        ),
        (
            "deeppink",
            Color {
                red: 255,
                green: 20,
                blue: 147,
            },
        ),
        (
            "grey",
            Color {
                red: 128,
                green: 128,
                blue: 128,
            },
        ),
        (
            "steelblue",
            Color {
                red: 70,
                green: 130,
                blue: 180,
            },
        ),
        (
            "forestgreen",
            Color {
                red: 34,
                green: 139,
                blue: 34,
            },
        ),
        (
            "darkgray",
            Color {
                red: 169,
                green: 169,
                blue: 169,
            },
        ),
        (
            "lightcyan",
            Color {
                red: 224,
                green: 255,
                blue: 255,
            },
        ),
        (
            "silver",
            Color {
                red: 192,
                green: 192,
                blue: 192,
            },
        ),
        (
            "burlywood",
            Color {
                red: 222,
                green: 184,
                blue: 135,
            },
        ),
        (
            "blue",
            Color {
                red: 0,
                green: 0,
                blue: 255,
            },
        ),
        (
            "cyan",
            Color {
                red: 0,
                green: 255,
                blue: 255,
            },
        ),
        (
            "skyblue",
            Color {
                red: 135,
                green: 206,
                blue: 235,
            },
        ),
        (
            "mediumaquamarine",
            Color {
                red: 102,
                green: 205,
                blue: 170,
            },
        ),
        (
            "lightsteelblue",
            Color {
                red: 176,
                green: 196,
                blue: 222,
            },
        ),
        (
            "khaki",
            Color {
                red: 240,
                green: 230,
                blue: 140,
            },
        ),
        (
            "navy",
            Color {
                red: 0,
                green: 0,
                blue: 128,
            },
        ),
        (
            "pink",
            Color {
                red: 255,
                green: 192,
                blue: 203,
            },
        ),
        (
            "blueviolet",
            Color {
                red: 138,
                green: 43,
                blue: 226,
            },
        ),
        (
            "darkorchid",
            Color {
                red: 153,
                green: 50,
                blue: 204,
            },
        ),
        (
            "mintcream",
            Color {
                red: 245,
                green: 255,
                blue: 250,
            },
        ),
        (
            "chocolate",
            Color {
                red: 210,
                green: 105,
                blue: 30,
            },
        ),
        (
            "chartreuse",
            Color {
                red: 127,
                green: 255,
                blue: 0,
            },
        ),
        (
            "lime",
            Color {
                red: 0,
                green: 255,
                blue: 0,
            },
        ),
        (
            "mediumorchid",
            Color {
                red: 186,
                green: 85,
                blue: 211,
            },
        ),
        (
            "lavenderblush",
            Color {
                red: 255,
                green: 240,
                blue: 245,
            },
        ),
        (
            "mediumslateblue",
            Color {
                red: 123,
                green: 104,
                blue: 238,
            },
        ),
        (
            "darkorange",
            Color {
                red: 255,
                green: 140,
                blue: 0,
            },
        ),
        (
            "ghostwhite",
            Color {
                red: 248,
                green: 248,
                blue: 255,
            },
        ),
        (
            "fuchsia",
            Color {
                red: 255,
                green: 0,
                blue: 255,
            },
        ),
        (
            "moccasin",
            Color {
                red: 255,
                green: 228,
                blue: 181,
            },
        ),
        (
            "white",
            Color {
                red: 255,
                green: 255,
                blue: 255,
            },
        ),
        (
            "darkgrey",
            Color {
                red: 169,
                green: 169,
                blue: 169,
            },
        ),
        (
            "maroon",
            Color {
                red: 128,
                green: 0,
                blue: 0,
            },
        ),
        (
            "midnightblue",
            Color {
                red: 25,
                green: 25,
                blue: 112,
            },
        ),
        (
            "limegreen",
            Color {
                red: 50,
                green: 205,
                blue: 50,
            },
        ),
        (
            "lightcoral",
            Color {
                red: 240,
                green: 128,
                blue: 128,
            },
        ),
        (
            "hotpink",
            Color {
                red: 255,
                green: 105,
                blue: 180,
            },
        ),
        (
            "mistyrose",
            Color {
                red: 255,
                green: 228,
                blue: 225,
            },
        ),
        (
            "lightslategrey",
            Color {
                red: 119,
                green: 136,
                blue: 153,
            },
        ),
        (
            "goldenrod",
            Color {
                red: 218,
                green: 165,
                blue: 32,
            },
        ),
        (
            "mediumturquoise",
            Color {
                red: 72,
                green: 209,
                blue: 204,
            },
        ),
        (
            "seagreen",
            Color {
                red: 46,
                green: 139,
                blue: 87,
            },
        ),
        (
            "floralwhite",
            Color {
                red: 255,
                green: 250,
                blue: 240,
            },
        ),
        (
            "blanchedalmond",
            Color {
                red: 255,
                green: 235,
                blue: 205,
            },
        ),
        (
            "springgreen",
            Color {
                red: 0,
                green: 255,
                blue: 127,
            },
        ),
        (
            "lightyellow",
            Color {
                red: 255,
                green: 255,
                blue: 224,
            },
        ),
        (
            "navajowhite",
            Color {
                red: 255,
                green: 222,
                blue: 173,
            },
        ),
        (
            "gainsboro",
            Color {
                red: 220,
                green: 220,
                blue: 220,
            },
        ),
        (
            "greenyellow",
            Color {
                red: 173,
                green: 255,
                blue: 47,
            },
        ),
        (
            "deepskyblue",
            Color {
                red: 0,
                green: 191,
                blue: 255,
            },
        ),
        (
            "sandybrown",
            Color {
                red: 244,
                green: 164,
                blue: 96,
            },
        ),
        (
            "azure",
            Color {
                red: 240,
                green: 255,
                blue: 255,
            },
        ),
        (
            "brown",
            Color {
                red: 165,
                green: 42,
                blue: 42,
            },
        ),
        (
            "magenta",
            Color {
                red: 255,
                green: 0,
                blue: 255,
            },
        ),
        (
            "dimgrey",
            Color {
                red: 105,
                green: 105,
                blue: 105,
            },
        ),
        (
            "mediumvioletred",
            Color {
                red: 199,
                green: 21,
                blue: 133,
            },
        ),
        (
            "snow",
            Color {
                red: 255,
                green: 250,
                blue: 250,
            },
        ),
        (
            "yellow",
            Color {
                red: 255,
                green: 255,
                blue: 0,
            },
        ),
        (
            "gray",
            Color {
                red: 128,
                green: 128,
                blue: 128,
            },
        ),
        (
            "orangered",
            Color {
                red: 255,
                green: 69,
                blue: 0,
            },
        ),
        (
            "crimson",
            Color {
                red: 220,
                green: 20,
                blue: 60,
            },
        ),
        (
            "darkgreen",
            Color {
                red: 0,
                green: 100,
                blue: 0,
            },
        ),
        (
            "lightpink",
            Color {
                red: 255,
                green: 182,
                blue: 193,
            },
        ),
        (
            "mediumspringgreen",
            Color {
                red: 0,
                green: 250,
                blue: 154,
            },
        ),
        (
            "thistle",
            Color {
                red: 216,
                green: 191,
                blue: 216,
            },
        ),
        (
            "sienna",
            Color {
                red: 160,
                green: 82,
                blue: 45,
            },
        ),
        (
            "lightgrey",
            Color {
                red: 211,
                green: 211,
                blue: 211,
            },
        ),
        (
            "darkslateblue",
            Color {
                red: 72,
                green: 61,
                blue: 139,
            },
        ),
        (
            "lightsalmon",
            Color {
                red: 255,
                green: 160,
                blue: 122,
            },
        ),
        (
            "darkviolet",
            Color {
                red: 148,
                green: 0,
                blue: 211,
            },
        ),
        (
            "saddlebrown",
            Color {
                red: 139,
                green: 69,
                blue: 19,
            },
        ),
        (
            "darkcyan",
            Color {
                red: 0,
                green: 139,
                blue: 139,
            },
        ),
        (
            "olive",
            Color {
                red: 128,
                green: 128,
                blue: 0,
            },
        ),
        (
            "whitesmoke",
            Color {
                red: 245,
                green: 245,
                blue: 245,
            },
        ),
        (
            "beige",
            Color {
                red: 245,
                green: 245,
                blue: 220,
            },
        ),
        (
            "olivedrab",
            Color {
                red: 107,
                green: 142,
                blue: 35,
            },
        ),
    ],
};

pub fn from_str(text: &str) -> Option<Color> {
    COLORS.get(text).cloned()
}

// A stripped down `phf` crate fork.
//
// https://github.com/sfackler/rust-phf

use std::borrow::Borrow;
use std::hash::Hasher;

pub struct Map<V: 'static> {
    pub key: u64,
    pub disps: &'static [(u32, u32)],
    pub entries: &'static [(&'static str, V)],
}

impl<V> Map<V> {
    pub fn get(&self, key: &str) -> Option<&V> {
        let hash = hash(key, self.key);
        let index = get_index(hash, &*self.disps, self.entries.len());
        let entry = &self.entries[index as usize];
        let b = entry.0.borrow();
        if b == key {
            Some(&entry.1)
        } else {
            None
        }
    }
}

#[inline]
fn hash(x: &str, key: u64) -> u64 {
    let mut hasher = siphasher::sip::SipHasher13::new_with_keys(0, key);
    hasher.write(x.as_bytes());
    hasher.finish()
}

#[inline]
fn get_index(hash: u64, disps: &[(u32, u32)], len: usize) -> u32 {
    let (g, f1, f2) = split(hash);
    let (d1, d2) = disps[(g % (disps.len() as u32)) as usize];
    displace(f1, f2, d1, d2) % (len as u32)
}

#[inline]
fn split(hash: u64) -> (u32, u32, u32) {
    const BITS: u32 = 21;
    const MASK: u64 = (1 << BITS) - 1;

    (
        (hash & MASK) as u32,
        ((hash >> BITS) & MASK) as u32,
        ((hash >> (2 * BITS)) & MASK) as u32,
    )
}

#[inline]
fn displace(f1: u32, f2: u32, d1: u32, d2: u32) -> u32 {
    d2 + f1 * d1 + f2
}
